// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProMCDescription.proto

package promc.io;

public final class ProMCDescriptionFile {
  private ProMCDescriptionFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProMCDescriptionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 version = 1;
    /**
     * <code>required uint64 version = 1;</code>
     *
     * <pre>
     * ProMC version 
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>required uint64 version = 1;</code>
     *
     * <pre>
     * ProMC version 
     * </pre>
     */
    long getVersion();

    // required uint64 events = 2;
    /**
     * <code>required uint64 events = 2;</code>
     *
     * <pre>
     * number of events 
     * </pre>
     */
    boolean hasEvents();
    /**
     * <code>required uint64 events = 2;</code>
     *
     * <pre>
     * number of events 
     * </pre>
     */
    long getEvents();

    // required string description = 3;
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * description 
     * </pre>
     */
    boolean hasDescription();
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * description 
     * </pre>
     */
    java.lang.String getDescription();
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * description 
     * </pre>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    // required uint64 timestamp = 4;
    /**
     * <code>required uint64 timestamp = 4;</code>
     *
     * <pre>
     *  timestamp seince 1970 
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 4;</code>
     *
     * <pre>
     *  timestamp seince 1970 
     * </pre>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code promc.ProMCDescription}
   */
  public static final class ProMCDescription extends
      com.google.protobuf.GeneratedMessage
      implements ProMCDescriptionOrBuilder {
    // Use ProMCDescription.newBuilder() to construct.
    private ProMCDescription(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProMCDescription(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProMCDescription defaultInstance;
    public static ProMCDescription getDefaultInstance() {
      return defaultInstance;
    }

    public ProMCDescription getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProMCDescription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              events_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return promc.io.ProMCDescriptionFile.internal_static_promc_ProMCDescription_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return promc.io.ProMCDescriptionFile.internal_static_promc_ProMCDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              promc.io.ProMCDescriptionFile.ProMCDescription.class, promc.io.ProMCDescriptionFile.ProMCDescription.Builder.class);
    }

    public static com.google.protobuf.Parser<ProMCDescription> PARSER =
        new com.google.protobuf.AbstractParser<ProMCDescription>() {
      public ProMCDescription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProMCDescription(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProMCDescription> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    /**
     * <code>required uint64 version = 1;</code>
     *
     * <pre>
     * ProMC version 
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 version = 1;</code>
     *
     * <pre>
     * ProMC version 
     * </pre>
     */
    public long getVersion() {
      return version_;
    }

    // required uint64 events = 2;
    public static final int EVENTS_FIELD_NUMBER = 2;
    private long events_;
    /**
     * <code>required uint64 events = 2;</code>
     *
     * <pre>
     * number of events 
     * </pre>
     */
    public boolean hasEvents() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 events = 2;</code>
     *
     * <pre>
     * number of events 
     * </pre>
     */
    public long getEvents() {
      return events_;
    }

    // required string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * description 
     * </pre>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * description 
     * </pre>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string description = 3;</code>
     *
     * <pre>
     * description 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint64 timestamp = 4;
    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 4;</code>
     *
     * <pre>
     *  timestamp seince 1970 
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint64 timestamp = 4;</code>
     *
     * <pre>
     *  timestamp seince 1970 
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      version_ = 0L;
      events_ = 0L;
      description_ = "";
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEvents()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, events_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, events_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static promc.io.ProMCDescriptionFile.ProMCDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static promc.io.ProMCDescriptionFile.ProMCDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static promc.io.ProMCDescriptionFile.ProMCDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static promc.io.ProMCDescriptionFile.ProMCDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static promc.io.ProMCDescriptionFile.ProMCDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static promc.io.ProMCDescriptionFile.ProMCDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static promc.io.ProMCDescriptionFile.ProMCDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static promc.io.ProMCDescriptionFile.ProMCDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static promc.io.ProMCDescriptionFile.ProMCDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static promc.io.ProMCDescriptionFile.ProMCDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(promc.io.ProMCDescriptionFile.ProMCDescription prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code promc.ProMCDescription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements promc.io.ProMCDescriptionFile.ProMCDescriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return promc.io.ProMCDescriptionFile.internal_static_promc_ProMCDescription_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return promc.io.ProMCDescriptionFile.internal_static_promc_ProMCDescription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                promc.io.ProMCDescriptionFile.ProMCDescription.class, promc.io.ProMCDescriptionFile.ProMCDescription.Builder.class);
      }

      // Construct using promc.io.ProMCDescriptionFile.ProMCDescription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        events_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return promc.io.ProMCDescriptionFile.internal_static_promc_ProMCDescription_descriptor;
      }

      public promc.io.ProMCDescriptionFile.ProMCDescription getDefaultInstanceForType() {
        return promc.io.ProMCDescriptionFile.ProMCDescription.getDefaultInstance();
      }

      public promc.io.ProMCDescriptionFile.ProMCDescription build() {
        promc.io.ProMCDescriptionFile.ProMCDescription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public promc.io.ProMCDescriptionFile.ProMCDescription buildPartial() {
        promc.io.ProMCDescriptionFile.ProMCDescription result = new promc.io.ProMCDescriptionFile.ProMCDescription(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.events_ = events_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof promc.io.ProMCDescriptionFile.ProMCDescription) {
          return mergeFrom((promc.io.ProMCDescriptionFile.ProMCDescription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(promc.io.ProMCDescriptionFile.ProMCDescription other) {
        if (other == promc.io.ProMCDescriptionFile.ProMCDescription.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasEvents()) {
          setEvents(other.getEvents());
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000004;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasEvents()) {
          
          return false;
        }
        if (!hasDescription()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        promc.io.ProMCDescriptionFile.ProMCDescription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (promc.io.ProMCDescriptionFile.ProMCDescription) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 version = 1;
      private long version_ ;
      /**
       * <code>required uint64 version = 1;</code>
       *
       * <pre>
       * ProMC version 
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 version = 1;</code>
       *
       * <pre>
       * ProMC version 
       * </pre>
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <code>required uint64 version = 1;</code>
       *
       * <pre>
       * ProMC version 
       * </pre>
       */
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 version = 1;</code>
       *
       * <pre>
       * ProMC version 
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0L;
        onChanged();
        return this;
      }

      // required uint64 events = 2;
      private long events_ ;
      /**
       * <code>required uint64 events = 2;</code>
       *
       * <pre>
       * number of events 
       * </pre>
       */
      public boolean hasEvents() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 events = 2;</code>
       *
       * <pre>
       * number of events 
       * </pre>
       */
      public long getEvents() {
        return events_;
      }
      /**
       * <code>required uint64 events = 2;</code>
       *
       * <pre>
       * number of events 
       * </pre>
       */
      public Builder setEvents(long value) {
        bitField0_ |= 0x00000002;
        events_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 events = 2;</code>
       *
       * <pre>
       * number of events 
       * </pre>
       */
      public Builder clearEvents() {
        bitField0_ = (bitField0_ & ~0x00000002);
        events_ = 0L;
        onChanged();
        return this;
      }

      // required string description = 3;
      private java.lang.Object description_ = "";
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * description 
       * </pre>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * description 
       * </pre>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * description 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * description 
       * </pre>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * description 
       * </pre>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       *
       * <pre>
       * description 
       * </pre>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }

      // required uint64 timestamp = 4;
      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 4;</code>
       *
       * <pre>
       *  timestamp seince 1970 
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint64 timestamp = 4;</code>
       *
       * <pre>
       *  timestamp seince 1970 
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 4;</code>
       *
       * <pre>
       *  timestamp seince 1970 
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 4;</code>
       *
       * <pre>
       *  timestamp seince 1970 
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:promc.ProMCDescription)
    }

    static {
      defaultInstance = new ProMCDescription(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:promc.ProMCDescription)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_promc_ProMCDescription_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_promc_ProMCDescription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ProMCDescription.proto\022\005promc\"[\n\020ProMC" +
      "Description\022\017\n\007version\030\001 \002(\004\022\016\n\006events\030\002" +
      " \002(\004\022\023\n\013description\030\003 \002(\t\022\021\n\ttimestamp\030\004" +
      " \002(\004B \n\010promc.ioB\024ProMCDescriptionFile"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_promc_ProMCDescription_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_promc_ProMCDescription_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_promc_ProMCDescription_descriptor,
              new java.lang.String[] { "Version", "Events", "Description", "Timestamp", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
