# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProMCHeader.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProMCHeader.proto',
  package='promc',
  serialized_pb='\n\x11ProMCHeader.proto\x12\x05promc\"\xcb\x05\n\x0bProMCHeader\x12\x0b\n\x03id1\x18\x01 \x01(\x05\x12\x0b\n\x03id2\x18\x02 \x01(\x05\x12\x0f\n\x07pdf_id1\x18\x03 \x01(\x05\x12\x0f\n\x07pdf_id2\x18\x04 \x01(\x05\x12\n\n\x02x1\x18\x05 \x01(\x01\x12\n\n\x02x2\x18\x06 \x01(\x01\x12\x10\n\x08scalepdf\x18\x07 \x01(\x01\x12\x0c\n\x04pdf1\x18\x08 \x01(\x05\x12\x0c\n\x04pdf2\x18\t \x01(\x05\x12\x0b\n\x03\x65\x43M\x18\n \x01(\x01\x12\t\n\x01s\x18\x0b \x01(\x01\x12\x0c\n\x04name\x18\x0c \x01(\t\x12\x0c\n\x04\x63ode\x18\r \x01(\x05\x12\x15\n\rcross_section\x18\x0e \x01(\x01\x12\x1b\n\x13\x63ross_section_error\x18\x0f \x01(\x01\x12\x14\n\x0cMomentumUnit\x18\x10 \x01(\x05\x12\x12\n\nLengthUnit\x18\x11 \x01(\x05\x12\x18\n\x10NameMomentumUnit\x18\x12 \x01(\t\x12\x16\n\x0eNameLengthUnit\x18\x13 \x01(\t\x12\x0e\n\x06weight\x18\x14 \x01(\x01\x12\x18\n\x10requested_events\x18\x15 \x01(\x01\x12\x35\n\x0cparticleData\x18\x1e \x03(\x0b\x32\x1f.promc.ProMCHeader.ParticleData\x12+\n\x07metaInt\x18\x1f \x03(\x0b\x32\x1a.promc.ProMCHeader.MetaInt\x12/\n\tmetaFloat\x18  \x03(\x0b\x32\x1c.promc.ProMCHeader.MetaFloat\x1ag\n\x0cParticleData\x12\n\n\x02id\x18\x01 \x02(\x11\x12\x0c\n\x04mass\x18\x02 \x02(\x01\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\r\n\x05width\x18\x04 \x01(\x02\x12\x10\n\x08lifetime\x18\x05 \x01(\x02\x12\x0e\n\x06\x63harge\x18\x06 \x01(\x11\x1a%\n\x07MetaInt\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x12\x1a\'\n\tMetaFloat\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x01\x42\x1b\n\x08promc.ioB\x0fProMCHeaderFile')




_PROMCHEADER_PARTICLEDATA = _descriptor.Descriptor(
  name='ParticleData',
  full_name='promc.ProMCHeader.ParticleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='promc.ProMCHeader.ParticleData.id', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mass', full_name='promc.ProMCHeader.ParticleData.mass', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='promc.ProMCHeader.ParticleData.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='promc.ProMCHeader.ParticleData.width', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lifetime', full_name='promc.ProMCHeader.ParticleData.lifetime', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='charge', full_name='promc.ProMCHeader.ParticleData.charge', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=561,
  serialized_end=664,
)

_PROMCHEADER_METAINT = _descriptor.Descriptor(
  name='MetaInt',
  full_name='promc.ProMCHeader.MetaInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='promc.ProMCHeader.MetaInt.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='promc.ProMCHeader.MetaInt.value', index=1,
      number=2, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=666,
  serialized_end=703,
)

_PROMCHEADER_METAFLOAT = _descriptor.Descriptor(
  name='MetaFloat',
  full_name='promc.ProMCHeader.MetaFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='promc.ProMCHeader.MetaFloat.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='promc.ProMCHeader.MetaFloat.value', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=705,
  serialized_end=744,
)

_PROMCHEADER = _descriptor.Descriptor(
  name='ProMCHeader',
  full_name='promc.ProMCHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id1', full_name='promc.ProMCHeader.id1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id2', full_name='promc.ProMCHeader.id2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pdf_id1', full_name='promc.ProMCHeader.pdf_id1', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pdf_id2', full_name='promc.ProMCHeader.pdf_id2', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x1', full_name='promc.ProMCHeader.x1', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x2', full_name='promc.ProMCHeader.x2', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scalepdf', full_name='promc.ProMCHeader.scalepdf', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pdf1', full_name='promc.ProMCHeader.pdf1', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pdf2', full_name='promc.ProMCHeader.pdf2', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eCM', full_name='promc.ProMCHeader.eCM', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s', full_name='promc.ProMCHeader.s', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='promc.ProMCHeader.name', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='promc.ProMCHeader.code', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cross_section', full_name='promc.ProMCHeader.cross_section', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cross_section_error', full_name='promc.ProMCHeader.cross_section_error', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MomentumUnit', full_name='promc.ProMCHeader.MomentumUnit', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LengthUnit', full_name='promc.ProMCHeader.LengthUnit', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NameMomentumUnit', full_name='promc.ProMCHeader.NameMomentumUnit', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NameLengthUnit', full_name='promc.ProMCHeader.NameLengthUnit', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='promc.ProMCHeader.weight', index=19,
      number=20, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requested_events', full_name='promc.ProMCHeader.requested_events', index=20,
      number=21, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='particleData', full_name='promc.ProMCHeader.particleData', index=21,
      number=30, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metaInt', full_name='promc.ProMCHeader.metaInt', index=22,
      number=31, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metaFloat', full_name='promc.ProMCHeader.metaFloat', index=23,
      number=32, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PROMCHEADER_PARTICLEDATA, _PROMCHEADER_METAINT, _PROMCHEADER_METAFLOAT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=744,
)

_PROMCHEADER_PARTICLEDATA.containing_type = _PROMCHEADER;
_PROMCHEADER_METAINT.containing_type = _PROMCHEADER;
_PROMCHEADER_METAFLOAT.containing_type = _PROMCHEADER;
_PROMCHEADER.fields_by_name['particleData'].message_type = _PROMCHEADER_PARTICLEDATA
_PROMCHEADER.fields_by_name['metaInt'].message_type = _PROMCHEADER_METAINT
_PROMCHEADER.fields_by_name['metaFloat'].message_type = _PROMCHEADER_METAFLOAT
DESCRIPTOR.message_types_by_name['ProMCHeader'] = _PROMCHEADER

class ProMCHeader(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class ParticleData(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PROMCHEADER_PARTICLEDATA

    # @@protoc_insertion_point(class_scope:promc.ProMCHeader.ParticleData)

  class MetaInt(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PROMCHEADER_METAINT

    # @@protoc_insertion_point(class_scope:promc.ProMCHeader.MetaInt)

  class MetaFloat(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PROMCHEADER_METAFLOAT

    # @@protoc_insertion_point(class_scope:promc.ProMCHeader.MetaFloat)
  DESCRIPTOR = _PROMCHEADER

  # @@protoc_insertion_point(class_scope:promc.ProMCHeader)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\010promc.ioB\017ProMCHeaderFile')
# @@protoc_insertion_point(module_scope)
