# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProMCStat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProMCStat.proto',
  package='promc',
  serialized_pb='\n\x0fProMCStat.proto\x12\x05promc\"\xf0\x02\n\tProMCStat\x12\x19\n\x11nevents_requested\x18\x01 \x01(\x05\x12\x16\n\x0enevents_failed\x18\x02 \x01(\x05\x12!\n\x19\x63ross_section_accumulated\x18\x03 \x01(\x01\x12\'\n\x1f\x63ross_section_error_accumulated\x18\x04 \x01(\x01\x12\x1e\n\x16luminosity_accumulated\x18\x05 \x01(\x01\x12\x0e\n\x06nTried\x18\x06 \x01(\x05\x12\x11\n\tnSelected\x18\x07 \x01(\x05\x12\x11\n\tnAccepted\x18\x08 \x01(\x05\x12\x31\n\x0bprocessData\x18\n \x03(\x0b\x32\x1c.promc.ProMCStat.ProcessData\x1a[\n\x0bProcessData\x12\n\n\x02id\x18\x01 \x02(\x11\x12\x15\n\rcross_section\x18\x02 \x02(\x01\x12\x1b\n\x13\x63ross_section_error\x18\x03 \x02(\x01\x12\x0c\n\x04name\x18\x04 \x02(\tB\x19\n\x08promc.ioB\rProMCStatFile')




_PROMCSTAT_PROCESSDATA = _descriptor.Descriptor(
  name='ProcessData',
  full_name='promc.ProMCStat.ProcessData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='promc.ProMCStat.ProcessData.id', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cross_section', full_name='promc.ProMCStat.ProcessData.cross_section', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cross_section_error', full_name='promc.ProMCStat.ProcessData.cross_section_error', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='promc.ProMCStat.ProcessData.name', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=304,
  serialized_end=395,
)

_PROMCSTAT = _descriptor.Descriptor(
  name='ProMCStat',
  full_name='promc.ProMCStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nevents_requested', full_name='promc.ProMCStat.nevents_requested', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nevents_failed', full_name='promc.ProMCStat.nevents_failed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cross_section_accumulated', full_name='promc.ProMCStat.cross_section_accumulated', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cross_section_error_accumulated', full_name='promc.ProMCStat.cross_section_error_accumulated', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='luminosity_accumulated', full_name='promc.ProMCStat.luminosity_accumulated', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nTried', full_name='promc.ProMCStat.nTried', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nSelected', full_name='promc.ProMCStat.nSelected', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nAccepted', full_name='promc.ProMCStat.nAccepted', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='processData', full_name='promc.ProMCStat.processData', index=8,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PROMCSTAT_PROCESSDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=395,
)

_PROMCSTAT_PROCESSDATA.containing_type = _PROMCSTAT;
_PROMCSTAT.fields_by_name['processData'].message_type = _PROMCSTAT_PROCESSDATA
DESCRIPTOR.message_types_by_name['ProMCStat'] = _PROMCSTAT

class ProMCStat(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class ProcessData(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PROMCSTAT_PROCESSDATA

    # @@protoc_insertion_point(class_scope:promc.ProMCStat.ProcessData)
  DESCRIPTOR = _PROMCSTAT

  # @@protoc_insertion_point(class_scope:promc.ProMCStat)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\010promc.ioB\rProMCStatFile')
# @@protoc_insertion_point(module_scope)
