# S.Chekanov


ifndef PROMC
$(error PROMC env variable is not set. Run setup.sh first)
endif


# set correct location of HEPMC library!
HEPMC_PREFIX =$(HEPMC)


include ${PROMC}/etc/config.mk
OPT2          = -g
CXXFLAGS      = $(OPT2) $(CPP_FLAGS)
LD            = $(CXX) 
LDFLAGS       = $(OPT2)
SOFLAGS       = -shared
OutPutOpt     = -o  
LIBS         += -L$(PROMC)/lib -lprotoc -lprotobuf -lprotobuf-lite -lcbook -lz
LIBS         += -L./stdhep/lib -lstdhepC -lFmcfio

INCLUDE1= -I./src
INCLUDE2= -I./stdhep/mcfio -I./stdhep/src/inc
INCLUDE3= -I$(PROMC)/include

Tasks:     clean prepare stdhep2promc

prepare:
	@cp -rf $(PROMC)/src .
	@cp -rf $(PROMC)/proto/promc proto
	echo "Prepare the ProMC default layout in src/";

COPY := $(shell cp -rf ${PROMC}/src .)


SOURCE_FILES1 := $(shell ls -1 stdhep2promc.cc src/*.cc)

# build object files 
objects1       = $(patsubst %.cc,%.o,$(SOURCE_FILES1))


%.o: %.cc
	$(CXX) $(OPT) $(CXXFLAGS) $(INCLUDE1) $(INCLUDE2) $(INCLUDE3) -o $@ -c $<
%.o: %.c
	$(CXX) $(OPT) $(CXXFLAGS) $(INCLUDE1) $(INCLUDE2) $(INCLUDE3) -o $@ -c $<


LIBOBJS = $(patsubst %.cc,%.o,$(SOURCE_FILES))

stdhep2promc: $(objects1)
	$(LD) $(LDFLAGS) $^ $(LIBS) $(OutPutOpt)$@

clean:
	        @rm -f *.o *~ stdhep2promc; rm -rf src; cd stdhep; make realclean;  echo "Clear.." 
