SHELL=/bin/sh
DIR_SHARE=/users/chekanov/work/ProMC/ProMC/share
DIR_CBOOK=/users/chekanov/work/ProMC/ProMC/cbook
DIR_CURRENT=/users/chekanov/work/ProMC/ProMC
AR=ar
ARCH=x86_64
CXX=g++
CPP_COMP=g++
CPP_FLAGS= -ansi -fPIC -Wall -c
CC=gcc
