# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProMC.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProMC.proto',
  package='promc',
  serialized_pb='\n\x0bProMC.proto\x12\x05promc\"\xa4\x02\n\nProMCEvent\x12&\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x17.promc.ProMCEvent.Event\x12.\n\tparticles\x18\x02 \x01(\x0b\x32\x1b.promc.ProMCEvent.Particles\x1aI\n\x05\x45vent\x12\x0e\n\x06Number\x18\x01 \x01(\x05\x12\x12\n\nProcess_ID\x18\x02 \x01(\x05\x12\r\n\x05\x66\x64\x61ta\x18\x03 \x03(\x02\x12\r\n\x05idata\x18\x04 \x03(\x12\x1as\n\tParticles\x12\x0e\n\x02id\x18\x01 \x03(\rB\x02\x10\x01\x12\x12\n\x06pdg_id\x18\x02 \x03(\x11\x42\x02\x10\x01\x12\x12\n\x06\x45nergy\x18\x03 \x03(\x12\x42\x02\x10\x01\x12\x0e\n\x02Px\x18\x04 \x03(\x12\x42\x02\x10\x01\x12\x0e\n\x02Py\x18\x05 \x03(\x12\x42\x02\x10\x01\x12\x0e\n\x02Pz\x18\x06 \x03(\x12\x42\x02\x10\x01\x42\x11\n\x08promc.ioB\x05ProMC')




_PROMCEVENT_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='promc.ProMCEvent.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Number', full_name='promc.ProMCEvent.Event.Number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Process_ID', full_name='promc.ProMCEvent.Event.Process_ID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fdata', full_name='promc.ProMCEvent.Event.fdata', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idata', full_name='promc.ProMCEvent.Event.idata', index=3,
      number=4, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=125,
  serialized_end=198,
)

_PROMCEVENT_PARTICLES = _descriptor.Descriptor(
  name='Particles',
  full_name='promc.ProMCEvent.Particles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='promc.ProMCEvent.Particles.id', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='pdg_id', full_name='promc.ProMCEvent.Particles.pdg_id', index=1,
      number=2, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='Energy', full_name='promc.ProMCEvent.Particles.Energy', index=2,
      number=3, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='Px', full_name='promc.ProMCEvent.Particles.Px', index=3,
      number=4, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='Py', full_name='promc.ProMCEvent.Particles.Py', index=4,
      number=5, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='Pz', full_name='promc.ProMCEvent.Particles.Pz', index=5,
      number=6, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=200,
  serialized_end=315,
)

_PROMCEVENT = _descriptor.Descriptor(
  name='ProMCEvent',
  full_name='promc.ProMCEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='promc.ProMCEvent.event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='particles', full_name='promc.ProMCEvent.particles', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PROMCEVENT_EVENT, _PROMCEVENT_PARTICLES, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=315,
)

_PROMCEVENT_EVENT.containing_type = _PROMCEVENT;
_PROMCEVENT_PARTICLES.containing_type = _PROMCEVENT;
_PROMCEVENT.fields_by_name['event'].message_type = _PROMCEVENT_EVENT
_PROMCEVENT.fields_by_name['particles'].message_type = _PROMCEVENT_PARTICLES
DESCRIPTOR.message_types_by_name['ProMCEvent'] = _PROMCEVENT

class ProMCEvent(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Event(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PROMCEVENT_EVENT

    # @@protoc_insertion_point(class_scope:promc.ProMCEvent.Event)

  class Particles(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PROMCEVENT_PARTICLES

    # @@protoc_insertion_point(class_scope:promc.ProMCEvent.Particles)
  DESCRIPTOR = _PROMCEVENT

  # @@protoc_insertion_point(class_scope:promc.ProMCEvent)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\010promc.ioB\005ProMC')
_PROMCEVENT_PARTICLES.fields_by_name['id'].has_options = True
_PROMCEVENT_PARTICLES.fields_by_name['id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_PROMCEVENT_PARTICLES.fields_by_name['pdg_id'].has_options = True
_PROMCEVENT_PARTICLES.fields_by_name['pdg_id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_PROMCEVENT_PARTICLES.fields_by_name['Energy'].has_options = True
_PROMCEVENT_PARTICLES.fields_by_name['Energy']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_PROMCEVENT_PARTICLES.fields_by_name['Px'].has_options = True
_PROMCEVENT_PARTICLES.fields_by_name['Px']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_PROMCEVENT_PARTICLES.fields_by_name['Py'].has_options = True
_PROMCEVENT_PARTICLES.fields_by_name['Py']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_PROMCEVENT_PARTICLES.fields_by_name['Pz'].has_options = True
_PROMCEVENT_PARTICLES.fields_by_name['Pz']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
