# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProMCDescription.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProMCDescription.proto',
  package='promc',
  serialized_pb='\n\x16ProMCDescription.proto\x12\x05promc\"[\n\x10ProMCDescription\x12\x0f\n\x07version\x18\x01 \x02(\x04\x12\x0e\n\x06\x65vents\x18\x02 \x02(\x04\x12\x13\n\x0b\x64\x65scription\x18\x03 \x02(\t\x12\x11\n\ttimestamp\x18\x04 \x02(\x04\x42 \n\x08promc.ioB\x14ProMCDescriptionFile')




_PROMCDESCRIPTION = _descriptor.Descriptor(
  name='ProMCDescription',
  full_name='promc.ProMCDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='promc.ProMCDescription.version', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='events', full_name='promc.ProMCDescription.events', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='promc.ProMCDescription.description', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='promc.ProMCDescription.timestamp', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['ProMCDescription'] = _PROMCDESCRIPTION

class ProMCDescription(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROMCDESCRIPTION

  # @@protoc_insertion_point(class_scope:promc.ProMCDescription)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\010promc.ioB\024ProMCDescriptionFile')
# @@protoc_insertion_point(module_scope)
